# Generated by Django 5.0.2 on 2024-02-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='expiration_date',
            new_name='ends_in',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='name',
        ),
    ]
